### ISSUE TITLE
Refresh collaspe after adding elements to DOM 

### ISSUE THREAD

**Issue by sderrick** [danielstocks/jQuery-Collapse#103]
I need to add new elements to the collaspe set dynamically.  How do I refresh the set so the new elements will expand and collaspe?

**Comment by danielstocks** [comment]
hi @sderrick 

The only way to do get the new DOM elements is to the re-run the plugin.

I guess a `refresh` method would be a nice addition? API proposal:

```
var demo = new jQueryCollapse($("#demo")); // Initializing plugin
$("#demo").append(newDomElements)
demo.refresh(); // Add new DOM elements to plugin
```

Or maybe there is a way for the plugin to listen for a DOM mutation event and automatically refresh itself?

Suggestions?

**Comment by sderrick** [comment]
Daniel,

Is it OK to rerun the plugin?

What would be the difference between rerunning it and refreshing it?

thanks,

Scott

**Comment by danielstocks** [comment]
I think re-running the plugin could work for your use-case, but there might be un-intended consequences like events firing twice. Here is the code that is run during initialization: https://github.com/danielstocks/jQuery-Collapse/blob/master/src/jquery.collapse.js#L15.

The best thing would probably be to have some kind of refresh method as the browser support for https://caniuse.com/mutationobserver isn't great, and a lot of people are using this plugin for legacy applications.
