### ISSUE TITLE
Love this script! It fails badly in IE...

### ISSUE THREAD

**Issue by studioleland** [danielstocks/jQuery-Collapse#27]
Hey I would love to use this script on upcoming project but after some quick testing it fails in IE7, IE8 and IE9.

**Comment by LukeKirby** [comment]
Hi few years later but I've had the same issue in IE only where having a large number of collapsible elements (over 2000) on the page causes the browser to freeze. 

I tracked it down to the jQuery function wrapInner() which causes the styling of the elements to change thereby refreshing the entire DOM (typically 400ms per collapsible on my pc). I wanted to ask what exactly is the purpose of the <a> element added to the collapsible? src/jquery.collapse.js#L85

Without the wrapInner('<a href="#" />') part the performance is significantly improved in that the page now loads instantly. (aside from network transfer delay).
