### ISSUE TITLE
twitter bootstrap responsive toggle conflict 

### ISSUE THREAD

**Issue by agispas** [danielstocks/jQuery-Collapse#68]
I've copied your latest change for jquery.collapse.js ( 'collapsed' instead of 'open') from here 
https://github.com/danielstocks/jQuery-Collapse/blob/c8964af642d791811e765958ca5aa5a2b7302f00/src/jquery.collapse.js
and this code:

```
$(".accordion-example").collapse({
          accordion: true,

          open: function() {
            this.addClass("collapsed");
            this.css({ height: this.children().outerHeight() });
          },
          close: function() {
            this.css({ height: "0px" });
            this.removeClass("collapsed");
          }
        });
```

But this still doesn't solve the issue with the Bootstrap toggle from navigation.
What am I missing ? 
Thank you!

**Comment by danielstocks** [comment]
Planned on fixing in #102
