### ISSUE TITLE
how to open all accordian on button click

### ISSUE THREAD

**Issue by myselfgaurav** [danielstocks/jQuery-Collapse#84]
how to open all accordian on button click

**Comment by danielstocks** [comment]
https://github.com/danielstocks/jQuery-Collapse#triggering-events

**Comment by outline4** [comment]
Do I need to initialize the plugin with js in order to get this working?

**Comment by danielstocks** [comment]
No it should work as long as the plugin has loaded.

```js
// Opens all section when clicking <button id="my-button>
$("#my-buttton").click(function() {
  $("#collapsible-container").trigger("open")
});
```
