### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by yellowled** [danielstocks/jQuery-Collapse#86]
Right now, a lot of people are switching from Bower to just npm as their package manager. As far as I can see, jQuery-Collapse is only available via Bower. Would be nice to [publish it on npm](https://docs.npmjs.com/getting-started/publishing-npm-packages) as well.

**Comment by danielstocks** [comment]
https://www.npmjs.com/package/jquery-collapse

**Comment by yellowled** [comment]
:+1: Thanks!
