### ISSUE TITLE
Document/Example conflict on the use of open/close show/hide

### ISSUE THREAD

**Issue by whatsnewsisyphus** [danielstocks/jQuery-Collapse#90]
Hello,
The example on the page uses open/close to scrollup/scrolldown the collapsible container, while the document suggests using show/hide. 

Using show hide methods as suggested in the readme does not scroll up / down, probably because the open close methods get to display:none / display:block first.

What would be the correct way to make it scroll up/down?

**Comment by danielstocks** [comment]
Are you talking about this page? http://webcloud.se/jQuery-Collapse/ 
And if so, are you talking about the CSS3 Animations?

**Comment by whatsnewsisyphus** [comment]
Hello Daniel, I mean that in the custom show/hide, it uses the following, but that doesn't work to animate unless I'm missing a css override somewhere.
```
new jQueryCollapse($("#custom-show-hide-example"), {
  open: function() {
    this.slideDown(150);
  },
  close: function() {
    this.slideUp(150);
  }
});
```
and in the README.MD in githib, it uses the following which works out of the box
```
$("#demo").collapse({
  show: function() {
    // The context of 'this' is applied to
    // the collapsed details in a jQuery wrapper 
    this.slideDown(100);
  },
  hide: function() {
    this.slideUp(100);
  },
  accordion: true,
  persist: true
});
```

**Comment by danielstocks** [comment]
Where did you find the second code example? There is no "show" and "hide" methods. The correct code should be like this:

```
$("#demo").collapse({
  open: function() {
    this.slideDown(100);
  },
  close: function() {
    this.slideUp(100);
  }
});
```

**Comment by danielstocks** [comment]
Ok i see what happened now, you followed an old link to an old version of the API, which used to have show, hide methods.

I will update the link to point to the latest version of README

Thanks for your feedback

**Comment by whatsnewsisyphus** [comment]
I found out what happened, it was a link to an old version of your  [readme](https://github.com/danielstocks/jQuery-Collapse/blob/523c08f9747b42251e8a1fd84154ed0a2e1b979a/README.md) where you used the show and hide. *edit. you figured it out as well
