### ISSUE TITLE
Selectize + Collapse

### ISSUE THREAD

**Issue by dotmilk** [danielstocks/jQuery-Collapse#92]
I've already ran [selectize](http://selectize.github.io/selectize.js/) and have 'html' that looks like this
```
<container #collapse-these>
  <label></label>
  <select hidden by selectize></select>
  <div inserted by selective></div>
  <label></label>
  <select hidden by selectize></select>
  <div inserted by selective></div>
</container>
```
Is there a way to have a query for the header/summary as well as one for the element to collapse:

As far as i can tell i can only point it to the summary if there is some strange nesting, not at the thing i want to collapse as well. Right now it will collapse the already hidden selects, leaving the divs that had been inserted by selectize visible.

```
<container #collapse-these>
  <label></label> <-- summary
  <select hidden by selectize></select> <--- should be ignored
  <div inserted by selective></div> <-- needs to collapse
  <label></label> <-- summary
  <select hidden by selectize></select> <---should be ignored
  <div inserted by selective></div> <-- needs to collapse
</container>
```

**Comment by dotmilk** [comment]
Or perhaps a way to inform it to ignore things after the summary/header that are already hidden (display: none)?

**Comment by dotmilk** [comment]
If i change the plugin $details to next next and pass a query like '> :nth-child(3n-2)' then it works like I would expect
```
    $.extend(this, {
      isOpen : false,
      $summary : $el.attr("data-collapse-summary",""),
        $details : $el.next().next(),
      options: parent.options,
      parent: parent
    })
```

**Comment by danielstocks** [comment]
Great, I'm happy that you found a solution!

**Comment by dotmilk** [comment]
Well i wouldn't consider breaking the plugin for other instances that aren't this case on page a solution.
